export const skills = [
  { name: "Next.js", highlight: true },
  { name: "React.js", highlight: true },
  { name: "JavaScript", highlight: true },
  { name: "TypeScript", highlight: true },
  { name: "Express", highlight: false },
  { name: "Tailwind", highlight: false },
  { name: "SCSS", highlight: false },
  { name: "Jest", highlight: false },
  { name: "Puppeteer", highlight: false },
  { name: "MySQL", highlight: false },
  { name: "MongoDB", highlight: false },
  { name: "Docker", highlight: true },
  { name: "Builder.io", highlight: false },
  { name: "Figma", highlight: false },
  { name: "Swagger", highlight: false },
  { name: "MongoDB Tools", highlight: false },
  { name: "Google Analytics", highlight: true },
  { name: "SEO", highlight: true },
  { name: "Firebase", highlight: false },
  { name: "SAAS", highlight: false },
  { name: "PAAS", highlight: false },
  { name: "Agile/Scrum", highlight: false },
  { name: "Debugging", highlight: false },
  { name: "Leadership", highlight: false },
  { name: "Growth mentality", highlight: false },
  { name: "Flexibility", highlight: false },
];

export const upComingSkills = [
  { name: "AWS", highlight: true },
  { name: "Node.js", highlight: true },
  { name: "Nginx", highlight: false },
  { name: "Kubernetes", highlight: false },
];
