export { default as About } from './About';
export { default as Contact } from './Contact';
export { default as Experience } from './Experience';
export { default as Projects } from './Projects';
export { default as Skills } from './Skills';
export { default as DarkMode } from './DarkMode';
export { default as Header } from './Header';
export { default as Footer } from './Footer';
export { default as Home } from './Home';